"""add delivery customer fields

Revision ID: 3505193c6e28
Revises: ac8ba2cd2c81
Create Date: 2026-02-04 20:18:34.913831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3505193c6e28'
down_revision: Union[str, Sequence[str], None] = 'ac8ba2cd2c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_customer_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('delivery_customer_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_customer_phone')
    op.drop_column('orders', 'delivery_customer_name')
    # ### end Alembic commands ###
