"""allow_null_company_id_for_global_rbac

Revision ID: 3d4f17091f82
Revises: 68ac4f51243a
Create Date: 2026-01-29 19:52:33.645471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d4f17091f82'
down_revision: Union[str, Sequence[str], None] = '68ac4f51243a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission_categories', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('permissions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production_event_input_batches', 'quantity_consumed',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=True)
    op.alter_column('production_event_input_batches', 'cost_attributed',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=True)
    op.drop_constraint('production_event_input_batches_production_event_input_id_fkey', 'production_event_input_batches', type_='foreignkey')
    op.create_foreign_key(None, 'production_event_input_batches', 'production_event_inputs', ['production_event_input_id'], ['id'])
    op.drop_index('uq_products_company_name_active', table_name='products', postgresql_where='(is_active = true)')
    op.add_column('recipes', sa.Column('recipe_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'recipe_type')
    op.create_index('uq_products_company_name_active', 'products', ['company_id', 'name'], unique=True, postgresql_where='(is_active = true)')
    op.drop_constraint(None, 'production_event_input_batches', type_='foreignkey')
    op.create_foreign_key('production_event_input_batches_production_event_input_id_fkey', 'production_event_input_batches', 'production_event_inputs', ['production_event_input_id'], ['id'], ondelete='CASCADE')
    op.alter_column('production_event_input_batches', 'cost_attributed',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=False)
    op.alter_column('production_event_input_batches', 'quantity_consumed',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=False)
    op.alter_column('permissions', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('permission_categories', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
