"""add_inventory_count_tables

Revision ID: 43add55754a2
Revises: 569a459d77e1
Create Date: 2026-01-15 18:39:36.213551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43add55754a2'
down_revision: Union[str, Sequence[str], None] = '569a459d77e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_counts',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'APPLIED', name='inventorycountstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_counts_branch_id'), 'inventory_counts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventory_counts_company_id'), 'inventory_counts', ['company_id'], unique=False)
    op.create_table('inventory_count_items',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('count_id', sa.Uuid(), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['inventory_counts.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_count_items_count_id'), 'inventory_count_items', ['count_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_count_items_count_id'), table_name='inventory_count_items')
    op.drop_table('inventory_count_items')
    op.drop_index(op.f('ix_inventory_counts_company_id'), table_name='inventory_counts')
    op.drop_index(op.f('ix_inventory_counts_branch_id'), table_name='inventory_counts')
    op.drop_table('inventory_counts')
    # ### end Alembic commands ###
