"""add_ingredient_id_to_modifier_recipe_item

Revision ID: 523591746bf4
Revises: 43add55754a2
Create Date: 2026-01-15 19:11:35.696267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523591746bf4'
down_revision: Union[str, Sequence[str], None] = '43add55754a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modifier_recipe_items', sa.Column('ingredient_id', sa.Uuid(), nullable=True))
    op.alter_column('modifier_recipe_items', 'ingredient_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'modifier_recipe_items', 'ingredients', ['ingredient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modifier_recipe_items', type_='foreignkey')
    op.alter_column('modifier_recipe_items', 'ingredient_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('modifier_recipe_items', 'ingredient_id')
    # ### end Alembic commands ###
