"""add_ingredient_type_and_production_event

Revision ID: 569a459d77e1
Revises: 77941f48bc5c
Create Date: 2026-01-15 18:24:19.088952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569a459d77e1'
down_revision: Union[str, Sequence[str], None] = '77941f48bc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('input_ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('input_quantity', sa.Float(), nullable=False),
    sa.Column('input_cost_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('output_ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('output_quantity', sa.Float(), nullable=False),
    sa.Column('calculated_unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['input_ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['output_ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_events_company_id'), 'production_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_production_events_input_ingredient_id'), 'production_events', ['input_ingredient_id'], unique=False)
    op.create_index(op.f('ix_production_events_output_ingredient_id'), 'production_events', ['output_ingredient_id'], unique=False)
    
    # Manually create the enum type
    ingredient_type = sa.Enum('RAW', 'PROCESSED', name='ingredienttype')
    ingredient_type.create(op.get_bind(), checkfirst=True)
    
    op.add_column('ingredients', sa.Column('type', ingredient_type, nullable=False, server_default='RAW'))
    # Remove server_default after creation if not needed provided usage aligns
    op.alter_column('ingredients', 'type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'type')
    sa.Enum(name='ingredienttype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_production_events_output_ingredient_id'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_input_ingredient_id'), table_name='production_events')
    op.drop_index(op.f('ix_production_events_company_id'), table_name='production_events')
    op.drop_table('production_events')
    # ### end Alembic commands ###
