"""add_delivery_tracking_fields

Revision ID: 5b4c496bfa1f
Revises: 6fe48736a469
Create Date: 2026-01-11 16:29:07.625626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b4c496bfa1f'
down_revision: Union[str, Sequence[str], None] = '6fe48736a469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_delivered', sa.Integer(), nullable=False),
    sa.Column('total_cancelled', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('closing_notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_shifts_date', 'delivery_shifts', ['company_id', 'started_at'], unique=False)
    op.create_index('idx_delivery_shifts_driver', 'delivery_shifts', ['company_id', 'delivery_person_id'], unique=False)
    op.create_index(op.f('ix_delivery_shifts_branch_id'), 'delivery_shifts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_delivery_shifts_company_id'), 'delivery_shifts', ['company_id'], unique=False)
    op.create_index(op.f('ix_delivery_shifts_delivery_person_id'), 'delivery_shifts', ['delivery_person_id'], unique=False)
    op.alter_column('customers', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # op.drop_constraint('customers_company_id_phone_key', 'customers', type_='unique')
    # op.create_unique_constraint('uq_customer_phone_company', 'customers', ['company_id', 'phone'])
    op.add_column('orders', sa.Column('delivery_person_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('picked_up_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.alter_column('orders', 'delivery_address',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_delivery_person_id'), 'orders', ['delivery_person_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['delivery_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_delivery_person_id'), table_name='orders')
    op.alter_column('orders', 'delivery_address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'picked_up_at')
    op.drop_column('orders', 'assigned_at')
    op.drop_column('orders', 'delivery_person_id')
    op.drop_constraint('uq_customer_phone_company', 'customers', type_='unique')
    op.create_unique_constraint('customers_company_id_phone_key', 'customers', ['company_id', 'phone'])
    op.alter_column('customers', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_delivery_shifts_delivery_person_id'), table_name='delivery_shifts')
    op.drop_index(op.f('ix_delivery_shifts_company_id'), table_name='delivery_shifts')
    op.drop_index(op.f('ix_delivery_shifts_branch_id'), table_name='delivery_shifts')
    op.drop_index('idx_delivery_shifts_driver', table_name='delivery_shifts')
    op.drop_index('idx_delivery_shifts_date', table_name='delivery_shifts')
    op.drop_table('delivery_shifts')
    # ### end Alembic commands ###
