"""create_ingredient_cost_history_table

Revision ID: 5c8e50e96d7e
Revises: cc772cb36aa0
Create Date: 2026-01-14 19:52:17.673641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c8e50e96d7e'
down_revision: Union[str, Sequence[str], None] = 'cc772cb36aa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_cost_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('previous_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('new_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_cost_history_ingredient_id'), 'ingredient_cost_history', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_cost_history_ingredient_id'), table_name='ingredient_cost_history')
    op.drop_table('ingredient_cost_history')
    # ### end Alembic commands ###
