"""add_recipes_tables

Revision ID: 5c9c5c869d77
Revises: a1b2c3d4e5f6
Create Date: 2025-12-31 21:57:56.027976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c9c5c869d77'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', name='uq_recipe_product')
    )
    op.create_index('idx_recipes_company_active', 'recipes', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_recipes_company_id'), 'recipes', ['company_id'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'ingredient_product_id', name='uq_recipe_item_ingredient')
    )
    op.create_index('idx_recipe_items_recipe', 'recipe_items', ['recipe_id'], unique=False)
    op.drop_index('idx_products_company_active_v2', table_name='products')
    op.drop_index('idx_products_company_category', table_name='products')
    op.create_index('idx_products_category', 'products', ['company_id', 'category_id'], unique=False)
    op.create_index('idx_products_company_active', 'products', ['company_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_products_company_active', table_name='products')
    op.drop_index('idx_products_category', table_name='products')
    op.create_index('idx_products_company_category', 'products', ['company_id', 'category_id'], unique=False)
    op.create_index('idx_products_company_active_v2', 'products', ['company_id', 'is_active'], unique=False)
    op.drop_index('idx_recipe_items_recipe', table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_recipes_company_id'), table_name='recipes')
    op.drop_index('idx_recipes_company_active', table_name='recipes')
    op.drop_table('recipes')
    # ### end Alembic commands ###
