"""rename type to ingredient_type

Revision ID: 5f47a05204c2
Revises: 523591746bf4
Create Date: 2026-01-15 20:00:32.274148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f47a05204c2'
down_revision: Union[str, Sequence[str], None] = '523591746bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create new Enum type
    new_enum = sa.Enum('RAW', 'PROCESSED', name='ingredient_type_enum')
    new_enum.create(op.get_bind())

    # 2. Add new column as nullable first to populate it
    # We use temporary String to facilitate data migration if needed, but going straight to Enum with USING is better if possible.
    # However, postgres needs the data to be valid for the enum.
    # So: Add as String, Update, Alter to Enum.
    op.add_column('ingredients', sa.Column('ingredient_type', sa.String(), nullable=True))
    
    # 3. Migrate data: Convert 'raw'/'processed' to 'RAW'/'PROCESSED'
    op.execute("UPDATE ingredients SET ingredient_type = UPPER(type::text)")
    op.execute("UPDATE ingredients SET ingredient_type = 'RAW' WHERE ingredient_type IS NULL")

    # 4. Alter column to use new Enum
    op.alter_column('ingredients', 'ingredient_type',
                    type_=new_enum,
                    postgresql_using='ingredient_type::ingredient_type_enum',
                    nullable=False)

    # 5. Drop old column and type
    op.drop_column('ingredients', 'type')
    # Use raw SQL to drop the old type as alembic doesn't have drop_type easily accessible for enums sometimes
    op.execute("DROP TYPE IF EXISTS ingredienttype")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('type', postgresql.ENUM('RAW', 'PROCESSED', name='ingredienttype'), autoincrement=False, nullable=False))
    op.drop_column('ingredients', 'ingredient_type')
    # ### end Alembic commands ###
