"""Increase numeric precision

Revision ID: 675cac6241d8
Revises: 823b6727e616
Create Date: 2026-01-17 18:23:54.424334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675cac6241d8'
down_revision: Union[str, Sequence[str], None] = '823b6727e616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_batches', 'quantity_initial',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('ingredient_batches', 'quantity_remaining',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=False)
    op.alter_column('ingredient_batches', 'cost_per_unit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('ingredient_batches', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('ingredients', 'current_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ingredients', 'last_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('production_event_inputs', 'cost_allocated',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('production_events', 'input_cost_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('production_events', 'calculated_unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_events', 'calculated_unit_cost',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('production_events', 'input_cost_total',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('production_event_inputs', 'cost_allocated',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('ingredients', 'last_cost',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ingredients', 'current_cost',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ingredient_batches', 'total_cost',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('ingredient_batches', 'cost_per_unit',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('ingredient_batches', 'quantity_remaining',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=3),
               existing_nullable=False)
    op.alter_column('ingredient_batches', 'quantity_initial',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.NUMERIC(precision=12, scale=3),
               existing_nullable=False)
    # ### end Alembic commands ###
