"""create_ingredient_batches_table

Revision ID: 77941f48bc5c
Revises: 5c8e50e96d7e
Create Date: 2026-01-15 16:49:39.041326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77941f48bc5c'
down_revision: Union[str, Sequence[str], None] = '5c8e50e96d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('quantity_initial', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_batches_acquired_at'), 'ingredient_batches', ['acquired_at'], unique=False)
    op.create_index(op.f('ix_ingredient_batches_branch_id'), 'ingredient_batches', ['branch_id'], unique=False)
    op.create_index(op.f('ix_ingredient_batches_ingredient_id'), 'ingredient_batches', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_ingredient_batches_is_active'), 'ingredient_batches', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_batches_is_active'), table_name='ingredient_batches')
    op.drop_index(op.f('ix_ingredient_batches_ingredient_id'), table_name='ingredient_batches')
    op.drop_index(op.f('ix_ingredient_batches_branch_id'), table_name='ingredient_batches')
    op.drop_index(op.f('ix_ingredient_batches_acquired_at'), table_name='ingredient_batches')
    op.drop_table('ingredient_batches')
    # ### end Alembic commands ###
