"""add output_batch_id to production_event

Revision ID: 823b6727e616
Revises: f5b93d7cc038
Create Date: 2026-01-17 15:32:12.223428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823b6727e616'
down_revision: Union[str, Sequence[str], None] = 'f5b93d7cc038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_events', sa.Column('output_batch_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'production_events', 'ingredient_batches', ['output_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production_events', type_='foreignkey')
    op.drop_column('production_events', 'output_batch_id')
    # ### end Alembic commands ###
