"""add_cancellation_fields

Revision ID: 9d98e5b6e5d8
Revises: add_created_by_id_orders
Create Date: 2026-02-08 18:40:37.871963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d98e5b6e5d8'
down_revision: Union[str, Sequence[str], None] = 'add_created_by_id_orders'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('orders', sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_processed_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('cancellation_requested_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_created_by_id'), 'orders', ['created_by_id'], unique=False)
    op.drop_constraint('fk_orders_created_by_id', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['cancellation_requested_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_created_by_id', 'orders', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_orders_created_by_id'), table_name='orders')
    op.drop_column('orders', 'cancellation_requested_by_id')
    op.drop_column('orders', 'cancellation_processed_at')
    op.drop_column('orders', 'cancellation_requested_at')
    op.drop_column('orders', 'cancellation_reason')
    op.drop_column('orders', 'cancellation_status')
    # ### end Alembic commands ###
