"""add_table_id_to_orders

Revision ID: ac8ba2cd2c81
Revises: 9ca592b555ad
Create Date: 2026-02-04 19:44:14.667585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac8ba2cd2c81'
down_revision: Union[str, Sequence[str], None] = '9ca592b555ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('removed_ingredients', sa.JSON(), nullable=True))
    op.add_column('orders', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_column('orders', 'table_id')
    op.drop_column('order_items', 'removed_ingredients')
    # ### end Alembic commands ###
