"""add inventory and cash closure tables

Revision ID: c4ee5ee4d128
Revises: 2260b86126b0
Create Date: 2026-01-07 17:37:51.159009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ee5ee4d128'
down_revision: Union[str, Sequence[str], None] = '2260b86126b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='printjobstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_jobs_company_id'), 'print_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_print_jobs_order_id'), 'print_jobs', ['order_id'], unique=False)
    op.create_index(op.f('ix_print_jobs_status'), 'print_jobs', ['status'], unique=False)
    op.create_table('cash_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('initial_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_card', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_transfer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('real_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('real_card', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('real_transfer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('real_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cashclosurestatus'), nullable=False),
    sa.Column('notes', sa.String(500), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_closures_branch_id'), 'cash_closures', ['branch_id'], unique=False)
    op.create_index(op.f('ix_cash_closures_company_id'), 'cash_closures', ['company_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_stock', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('bin_location', sa.String(50), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_inventory_branch_product')
    )
    op.create_index('idx_inventory_branch', 'inventory', ['branch_id'], unique=False)
    op.create_table('order_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_audits_order_id'), 'order_audits', ['order_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference_id', sa.String(100), nullable=True),
    sa.Column('reason', sa.String(255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('order_items', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('orders', 'tax_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.add_column('payments', sa.Column('company_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.create_index('idx_payments_company_date', 'payments', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_payments_order', 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_branch_id'), 'payments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'])
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('recipe_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               nullable=True)
    op.alter_column('recipe_items', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('recipes', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('recipe_items', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('recipe_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               nullable=False)
    op.alter_column('products', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_branch_id'), table_name='payments')
    op.drop_index('idx_payments_order', table_name='payments')
    op.drop_index('idx_payments_company_date', table_name='payments')
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('payments', 'user_id')
    op.drop_column('payments', 'branch_id')
    op.drop_column('payments', 'company_id')
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'tax_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('order_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('order_items', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_order_audits_order_id'), table_name='order_audits')
    op.drop_table('order_audits')
    op.drop_index('idx_inventory_branch', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_cash_closures_company_id'), table_name='cash_closures')
    op.drop_index(op.f('ix_cash_closures_branch_id'), table_name='cash_closures')
    op.drop_table('cash_closures')
    op.drop_index(op.f('ix_print_jobs_status'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_order_id'), table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_company_id'), table_name='print_jobs')
    op.drop_table('print_jobs')
    # ### end Alembic commands ###
