"""add_ingredient_cost_history

Revision ID: cc772cb36aa0
Revises: a002_add_recipe_fields
Create Date: 2026-01-14 19:38:56.773323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc772cb36aa0'
down_revision: Union[str, Sequence[str], None] = 'a002_add_recipe_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_inventory', 'stock',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('ingredient_inventory', 'min_stock',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('ingredient_transactions', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('ingredient_transactions', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('ingredients', 'current_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ingredients', 'last_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index('idx_ingredients_company', table_name='ingredients')
    op.drop_index('idx_ingredients_name', table_name='ingredients')
    op.drop_index('idx_ingredients_sku', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_category_id'), 'ingredients', ['category_id'], unique=False)
    op.create_index(op.f('ix_ingredients_company_id'), 'ingredients', ['company_id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_sku'), 'ingredients', ['sku'], unique=False)
    op.drop_constraint('fk_products_active_recipe', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'recipes', ['active_recipe_id'], ['id'])
    op.drop_index('idx_recipe_items_ingredient', table_name='recipe_items')
    op.drop_index('idx_recipe_items_recipe', table_name='recipe_items')
    op.drop_constraint('uq_recipe_item_ingredient', 'recipe_items', type_='unique')
    op.create_index(op.f('ix_recipe_items_company_id'), 'recipe_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_ingredient_id'), 'recipe_items', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_recipe_id'), 'recipe_items', ['recipe_id'], unique=False)
    op.drop_constraint('fk_recipe_items_recipe', 'recipe_items', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_items', 'recipes', ['recipe_id'], ['id'])
    op.alter_column('recipes', 'total_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.drop_index('idx_recipes_company_active', table_name='recipes')
    op.drop_constraint('uq_recipe_product', 'recipes', type_='unique')
    op.create_index(op.f('ix_recipes_product_id'), 'recipes', ['product_id'], unique=False)
    op.drop_column('recipes', 'description')
    op.drop_index('idx_unit_conversions_from_to', table_name='unit_conversions')
    op.create_index(op.f('ix_unit_conversions_from_unit'), 'unit_conversions', ['from_unit'], unique=False)
    op.create_index(op.f('ix_unit_conversions_to_unit'), 'unit_conversions', ['to_unit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_conversions_to_unit'), table_name='unit_conversions')
    op.drop_index(op.f('ix_unit_conversions_from_unit'), table_name='unit_conversions')
    op.create_index('idx_unit_conversions_from_to', 'unit_conversions', ['from_unit', 'to_unit'], unique=False)
    op.add_column('recipes', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recipes_product_id'), table_name='recipes')
    op.create_unique_constraint('uq_recipe_product', 'recipes', ['product_id'])
    op.create_index('idx_recipes_company_active', 'recipes', ['company_id', 'is_active'], unique=False)
    op.alter_column('recipes', 'total_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'recipe_items', type_='foreignkey')
    op.create_foreign_key('fk_recipe_items_recipe', 'recipe_items', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_recipe_items_recipe_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_ingredient_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_company_id'), table_name='recipe_items')
    op.create_unique_constraint('uq_recipe_item_ingredient', 'recipe_items', ['recipe_id', 'ingredient_id'])
    op.create_index('idx_recipe_items_recipe', 'recipe_items', ['recipe_id'], unique=False)
    op.create_index('idx_recipe_items_ingredient', 'recipe_items', ['ingredient_id'], unique=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('fk_products_active_recipe', 'products', 'recipes', ['active_recipe_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_ingredients_sku'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_company_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_category_id'), table_name='ingredients')
    op.create_index('idx_ingredients_sku', 'ingredients', ['sku'], unique=False)
    op.create_index('idx_ingredients_name', 'ingredients', ['name'], unique=False)
    op.create_index('idx_ingredients_company', 'ingredients', ['company_id'], unique=False)
    op.alter_column('ingredients', 'last_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ingredients', 'current_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('ingredient_transactions', 'balance_after',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('ingredient_transactions', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('ingredient_inventory', 'min_stock',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('ingredient_inventory', 'stock',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    # ### end Alembic commands ###
