"""ADD category table

Revision ID: dea652cfb15e
Revises: 9fd158ec5e9d
Create Date: 2025-12-18 17:21:18.753915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = 'dea652cfb15e'
down_revision: Union[str, Sequence[str], None] = '9fd158ec5e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='unique_category_name_per_company')
    )
    op.create_index('idx_categories_company_active', 'categories', ['company_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_categories_company_id'), 'categories', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_company_id'), table_name='categories')
    op.drop_index('idx_categories_company_active', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
