"""add_rbac_permission_system

Revision ID: ec9ce793ceea
Revises: dea652cfb15e
Create Date: 2025-12-22 18:21:13.703443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec9ce793ceea'
down_revision: Union[str, Sequence[str], None] = 'dea652cfb15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_categories',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='unique_category_code_per_company')
    )
    op.create_index('idx_perm_cat_company_active', 'permission_categories', ['company_id', 'is_active'], unique=False)
    op.create_index('idx_perm_cat_system', 'permission_categories', ['is_system', 'is_active'], unique=False)
    op.create_index(op.f('ix_permission_categories_company_id'), 'permission_categories', ['company_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='unique_role_code_per_company')
    )
    op.create_index('idx_roles_company_active', 'roles', ['company_id', 'is_active'], unique=False)
    op.create_index('idx_roles_hierarchy', 'roles', ['company_id', 'hierarchy_level'], unique=False)
    op.create_index('idx_roles_system', 'roles', ['is_system', 'is_active'], unique=False)
    op.create_index(op.f('ix_roles_company_id'), 'roles', ['company_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['permission_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='unique_permission_code_per_company')
    )
    op.create_index('idx_perm_active', 'permissions', ['company_id', 'is_active'], unique=False)
    op.create_index('idx_perm_company_category', 'permissions', ['company_id', 'category_id'], unique=False)
    op.create_index('idx_perm_resource_action', 'permissions', ['company_id', 'resource', 'action'], unique=False)
    op.create_index(op.f('ix_permissions_category_id'), 'permissions', ['category_id'], unique=False)
    op.create_index(op.f('ix_permissions_company_id'), 'permissions', ['company_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('permission_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
    )
    op.create_index('idx_role_perm_expires', 'role_permissions', ['expires_at'], unique=False)
    op.create_index('idx_role_perm_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_perm_role', 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.add_column('users', sa.Column('role_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index('idx_users_role', 'users', ['company_id', 'role_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index('idx_role_perm_role', table_name='role_permissions')
    op.drop_index('idx_role_perm_permission', table_name='role_permissions')
    op.drop_index('idx_role_perm_expires', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_permissions_company_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category_id'), table_name='permissions')
    op.drop_index('idx_perm_resource_action', table_name='permissions')
    op.drop_index('idx_perm_company_category', table_name='permissions')
    op.drop_index('idx_perm_active', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_roles_company_id'), table_name='roles')
    op.drop_index('idx_roles_system', table_name='roles')
    op.drop_index('idx_roles_hierarchy', table_name='roles')
    op.drop_index('idx_roles_company_active', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permission_categories_company_id'), table_name='permission_categories')
    op.drop_index('idx_perm_cat_system', table_name='permission_categories')
    op.drop_index('idx_perm_cat_company_active', table_name='permission_categories')
    op.drop_table('permission_categories')
    # ### end Alembic commands ###
