"""Add production event inputs

Revision ID: f5b93d7cc038
Revises: 5f47a05204c2
Create Date: 2026-01-16 20:05:44.943869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5b93d7cc038'
down_revision: Union[str, Sequence[str], None] = '5f47a05204c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_event_inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('production_event_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_allocated', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['production_event_id'], ['production_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_event_inputs_ingredient_id'), 'production_event_inputs', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_production_event_inputs_production_event_id'), 'production_event_inputs', ['production_event_id'], unique=False)
    op.add_column('production_events', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('production_events', 'input_ingredient_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_events', 'input_ingredient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('production_events', 'notes')
    op.drop_index(op.f('ix_production_event_inputs_production_event_id'), table_name='production_event_inputs')
    op.drop_index(op.f('ix_production_event_inputs_ingredient_id'), table_name='production_event_inputs')
    op.drop_table('production_event_inputs')
    # ### end Alembic commands ###
